server:
  port: 8004
spring:
  application:
    name: user-A
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
